### ISSUE TITLE
NCS Meter v1.0.1: YOU DONT HAVE PERMISSION TO REZ THIS METER... MESSAGE WAS SENT TO CREATOR!

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#96] opened 2021-10-07 18:33 UTC
when loading meter, i get this message

[11:31] NCS Meter v1.0.1: YOU DONT HAVE PERMISSION TO REZ THIS METER... MESSAGE WAS SENT TO CREATOR!

**Comment by AguilaKubrick** [comment] 2021-10-08 18:52
That message appears every time you drop your meter to the floor, we can't allow meters to be rezzed because they will load as if you are wearing it. So that happense when you try to replace your outfit by dragging a folder to your avi, we suggest to remove your meter prior to that, or to save your apparience without wearing the meter to avoid those messages.

**Comment by ezebongiovi** [comment] 2021-10-09 00:12
I'll close the issue since I cannot replicate it when wearing. Please feel free to re-open it with detailed steps to reproduce if it keeps happening on your end

**Closed as completed by ezebongiovi** 2021-10-09 00:12 UTC
Labels: bug, invalid

**Comment by MorphLupindo** [comment] 2021-10-29 00:16
[2021/10/26 15:17]  NCS Meter v1.0.1: YOU DONT HAVE PERMISSION TO REZ THIS METER... MESSAGE WAS SENT TO CREATOR!
[2021/10/28 07:42]  NCS Meter v1.0.1: YOU DONT HAVE PERMISSION TO REZ THIS METER... MESSAGE WAS SENT TO CREATOR!                

Both times, i was wearing the meter.  It wasn't dropped on the ground.
