### ISSUE TITLE
Swoon causes red ball to denote when it has hit, hook does not

### ISSUE THREAD

**Issue by MorphLupindo** [ncs-sl/support-en#43] opened 2021-09-29 16:23 UTC
Vampire healer has a clear indication of their racial recovery skill Swoon when it hits.
When Android healer hits with their racial recovery skill Hook, there is no red ball indication.

Here's the "red ball" effect:  https://gyazo.com/b57b9192d4153d8938466f6a8c2821d1

**Comment by ezebongiovi** [comment] 2021-10-01 01:23
That's because the **red ball** particle indicates exhaustion (your melee damage has been weakened). Hook does not do that, there's no effect rather than stealing your racial points.

I'm closing this one since it's not a bug

**Closed as completed by ezebongiovi** 2021-10-01 01:23 UTC
Labels: bug, wontfix

**Comment by MorphLupindo** [comment] 2021-10-01 01:24
ok
